Accept 8digit Hex color code
FifthTry/ftd pull request #221
Opened 2022-06-03 08:08 UTC by ADITIRAI290698

i will be converting alpha from hexa to deci.

2022-06-03 10:19 UTC, ADITIRAI290698 commented
i have corrected the code for alpha. please let me know if the change is right or wrong.

2022-06-03 13:00 UTC, amitu commented on src/p2/element.rs
> +        let iv = u64::from_str_radix(value_string, 16).unwrap();
Or return an error like you have done few lines down.

2022-06-03 13:01 UTC, amitu commented
@ADITIRAI290698 please fix the title of this PR. Also please try to add some tests for the feature and ensure tests are passing. Checkout interpreter.rs which has a lot of tests, you can add "integration test" there. You can also add add "unit test" in the same module where you have implemented the function.

2022-06-08 06:40 UTC, Arpita-Jaiswal commented
Remove the `examples/.packages/` folder and all it's contents

2022-06-08 06:42 UTC, Arpita-Jaiswal requested changes

2022-06-08 06:42 UTC, Arpita-Jaiswal commented on src/p2/element.rs
> +            alpha: dbg!(math::round::floor((iv & 0xff) as f64 / 255_f64, 1)) as f32,
Don't add a new library. Instead, add the required function.

2022-06-10 04:47 UTC, merged