Reworked caption body checks on components
FifthTry/ftd pull request #325
Opened 2022-08-01 16:01 UTC by Heulitig

- Revamped the code on caption body checks (**wip**)
- This is the continuation of an old PR which is closed now
- Old PR - https://github.com/FifthTry/ftd/pull/243
- Refer issue - https://github.com/FifthTry/ftd/issues/217

2022-08-05 07:17 UTC, amitu commented on src/component.rs
> +
Delete these comments please.

2022-08-10 11:22 UTC, AbrarNitk commented
@Heulitig did you test it with `fpm`?

2022-08-10 11:58 UTC, Heulitig commented
> @Heulitig did you test it with `fpm`?

I have used the local ftd in fpm in testing the other repos like ftd.dev, fpm.dev, doc-site, dotcom, df. And also did check against ftd tests and fpm tests.

2022-08-16 10:09 UTC, amitu commented
@Heulitig should I merge this?

2022-08-24 09:07 UTC, amitu commented
@Arpita-Jaiswal, @Heulitig, this PR is open since long. Can we merge it?

2022-08-27 11:36 UTC, Arpita-Jaiswal requested changes

2022-08-27 11:51 UTC, Heulitig commented on src/component.rs
> +    ) -> ftd::p1::Result<&'t ftd::p2::Thing> {
I didn't knew a similar function existed for this purpose. Using the existing one then and removing this function.

2022-08-29 07:22 UTC, amitu commented
@Arpita-Jaiswal should we merge this now?

2022-08-29 10:55 UTC, Arpita-Jaiswal commented
> @Arpita-Jaiswal should we merge this now?

Yep

2022-08-29 10:56 UTC, merged