Implement Check-Id in ftd. Test this by creating a hard coded id map
FifthTry/ftd pull request #391
Opened 2022-08-29 12:27 UTC by Heulitig

Discussion: [globally unique id](https://github.com/FifthTry/fpm/discussions/450)

2022-08-29 12:42 UTC, Heulitig commented
@Arpita-Jaiswal Im done with this PR can you merge this after reviewing it ?

2022-08-30 09:00 UTC, Arpita-Jaiswal commented
@Heulitig Please run `cargo fmt`.

2022-08-30 09:59 UTC, AbrarNitk requested changes

2022-08-30 09:59 UTC, AbrarNitk commented on src/p2/interpreter.rs
> +                );
@Heulitig Please remove `dbg!` statements.

2022-08-30 10:27 UTC, Arpita-Jaiswal requested changes

2022-08-30 10:27 UTC, Arpita-Jaiswal commented on src/p2/interpreter.rs
> +                );
```suggestion
                let linked_text =  capture_group_at(&cap, 1).trim();
                let actual_id = capture_group_at(&cap, 2).trim();
                let link = global_ids.get(actual_id).ok_or_else(<something>) // throw error if not found
                let replacement = format!(
                    "[{}]({}#{})", linked_text, link, slug::slugify(actual_id)
                );
```

2022-08-30 10:27 UTC, Arpita-Jaiswal commented on src/p2/interpreter.rs
> +                result = result.replacen(capture_group_at(&cap, 0), &replacement, 1);
Same as above

2022-08-30 10:27 UTC, Arpita-Jaiswal commented on src/p2/interpreter.rs
> +            dbg!(&section.name, &section.caption, section.is_commented);
Remove Logs

2022-09-01 07:04 UTC, Heulitig commented
@Arpita-Jaiswal 
Done with the changes do review this again

2022-09-07 08:51 UTC, merged